### ISSUE TITLE
Update Command Not Supported

### ISSUE THREAD

**Issue by Suleman-Elahi** [jokedst/CsvQuery#13]
![image](https://user-images.githubusercontent.com/24384996/41149054-6585980e-6abf-11e8-92ed-ddd262f3ab2d.png)

**Comment by jokedst** [comment]
That's because "THIS" is not a table, it's a view that points to the current document (if you parse several documents, THIS always works against the currently focused document).

The real table is called T1, T2, etc. There's a menu option to show them all.
UPDATE against views doesn't work in SQLite apparently.

Workarounds:
1. Use the real table name
2. Use MSSQL as backend instead of SQLIte :P

Possible long time fix:
I suppose there's no real reason why I can't simply rename the current table to THIS instead of using a view. Joins between e.g. T1 and T2 might break, but your use case is probably much more common that joining tables.
