### ISSUE TITLE
Make Plugin Multiple screen aware

### ISSUE THREAD

**Issue by whitten** [jokedst/CsvQuery#17]
I'd like to learn enough about this plug-in to be able to work on one of my own.

To this goal, I noticed that when I use the menus (under the Plugins Menu choosing CVSQuery then choosing one of the side menu choices, like "About" or "Settings" or  "Manual Parse Settings", this CvsQuery plugin pops up a window on the first monitor, and not on the second monitor where notepad++ is running.  

It does handle showing the "on-the-side" menu options on the second monitor, just the new windows it creates.

How do I learn how to find where the code "knows" to use the first monitor instead of the current monitor?

Thanks,
Dave Whitten
713-870-3834
whitten@netcom.com

**Comment by jokedst** [comment]
My plugin is based on a template you can find here: https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net

You're probably better of starting from that instead of my bastardized version ;)

That said, I usually just call Form.ShowDialog() without any settings. Where it pops up is Windows problem :P
