### ISSUE TITLE
Would be great to have generic ColN fieldnames when first line is not header

### ISSUE THREAD

**Issue by kreely** [jokedst/CsvQuery#24]
Hi,
This is potentially a great tool for me (and will probably still be quite useful even without the feature I'm talking about).

Only problem for me is that the first line of my CSV file is not a columns def and I don't want to have to add one to my file each time.
It would be really useful for me if I could have ColN as the fieldname if the first row is not a column def.

**Comment by jokedst** [comment]
It tries to detect if there is a header row. This does not work 100% though (and never will since it's sometimes impossible to detect).

If it detects it wrong, you can go to the menu Plugins->CsvQuery->"Manual parse settings" and uncheck the box for "First row is headers". Then you should get Col1,Col2 etc instead.
You'll have to enter the "Separator" correctly yourself in that dialog too, there is no detection for that either if you use manual settings (default is comma).

I've been thinking about putting a button for that dialog next to the "Read File" button or something...

**Comment by kreely** [comment]
> It tries to detect if there is a header row. This does not work 100% though (and never will since it's sometimes impossible to detect).
> 
> If it detects it wrong, you can go to the menu Plugins->CsvQuery->"Manual parse settings" and uncheck the box for "First row is headers". Then you should get Col1,Col2 etc instead.
> You'll have to enter the "Separator" correctly yourself in that dialog too, there is no detection for that either if you use manual settings (default is comma).
> 
> I've been thinking about putting a button for that dialog next to the "Read File" button or something...

Ah, that does work. I must have done something wrong before. Thanks.
I got one column with all of the text in it at a couple of points. I must have left of the separator or something. This may mean I can do what I need to do. Again, many thanks.
A cool tool.
