### ISSUE TITLE
CsvQuery not installing/working on version v8.3.3

### ISSUE THREAD

**Issue by doomoo** [jokedst/CsvQuery#34]
1) the CsvQuery is not showing in the plugin manager

2) When i try to install the CsvQuery v1.2.8-64 thru settings > Import > import plugins, it says it has installed the plugin and it will show after i restart the application. When i do this the plugin is not show up (opened notepad++ as administrator) .

![plugin not showing](https://user-images.githubusercontent.com/1125220/162900814-96540259-8efe-43db-a870-b7f8db265509.png)
n

Debug info
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.556
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll XMLTools.dll 

How can i fix this?

**Comment by wsuhoey** [comment]
Might be related to: #33

**Comment by vinsworldcom** [comment]
@doomoo @wsuhoey it is definitely related to #33.  Notepad++ 8.3 and above has made a change to support >2Gb files but requires plugins to update.  This plugin [code has been updated](https://github.com/jokedst/CsvQuery/commit/b2de6f1002b7d2b559f986dfff58fe8d4037c742), but the @jokedst has not yet released the next version to incorporate that change.

I think he's trying to find a way to detect which version of Notepad++ is running and use the appropriate data structures.  Basically, the fix will work with Notepad++ 8.3 and newer (crash on older versions) and without the fix it will work on Notepad++ 8.2 and older (crash on newer versions).  The author is trying to accommodate both instead of drawing a "line in the sand".

In the meantime, I was able to compile (through Github Actions) the latest code and called it [1.2.9 RC 1 available here](https://github.com/vinsworldcom/CsvQuery/releases/tag/v1.2.9) for manual install if you can't live without this plugin (as I could no longer).

Cheers.

**Comment by jokedst** [comment]
Ok ok ok, sorry, been busy.
I've created a 1.2.9 release that works, I'll start the process of getting it approved for the plugin manager.

**Comment by vinsworldcom** [comment]
@jokedst issue can be closed.
